"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GpxIcons-Garmin2Osmand.py']
DATA_FILES = [] #[('xsl', ['Gpx-Garmoin2Osmand.xls']), ('', [''])]
OPTIONS = {
    'argv_emulation': False,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
